name: simplicity_sdk
description: A Flutter package for deploying and interacting with smart contracts on simplicity-block
version: 1.0.0
homepage: https://github.com/affanshaikhsurab/simplicity_sdk

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

